application: fshackathon
version: 1
runtime: python
api_version: 1

handlers:
- url: /herenow
  static_files: herenow.html
  upload: herenow.html
  expiration: 0
- url: /static
  static_dir: static
  expiration: 0
- url: /.*
  script: main.py
  login: required
