application: fshackathon
version: 3
runtime: python
api_version: 1

handlers:
- url: /herenow
  static_files: herenow.html
  upload: herenow.html
- url: /static
  static_dir: static
- url: /.*
  script: main.py
  login: required